### PR TITLE
Merge to master

### PR DESCRIPTION
**Pull request by Abdusaid10**

### CODE REVIEW

**Comment by JamesOkunlade** [comment]
James working on it.

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
Hello @Abdusaid10 ,

Great work writing those tests. Works perfectly for the case.

A quick refactoring you should do though. Rather than having to declare your array over and over again in your differents tests, use the `let` to declare an array before your tests and you can call it in your tests. If you need help using the `let` refer to [this](https://github.com/rubocop-hq/rspec-style-guide#let-blocks).

Also, you should write a descriptive README.md for this project. Do well to include your name as the author.

Request for a re-review when you're done.

Happy coding!

**Comment by bellom** [comment]
## Currently reviewing this PR

**Review by bellom — APPROVED** [review]
Hi @Abdusaid10,
Good job making all the necessary changes from the previous review.
#### Congrats !
But before merging to master, i trust you can do the following; 
 - kindly leave one empty line between feature, context or describe blocks. Do not leave empty line after the last such block in a group. [checkout this article to fix the issue](https://github.com/rubocop-hq/rspec-style-guide#empty-lines-between-describes).

Goodluck in the next project.

**Pull request merged**
